### ISSUE TITLE
[extract_cell] add identifier of cell label to fov_results

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish#15]
The function `extract_cell` allows combining spot/foci detection results and cell/nuclei segmentation. 

Cell segmentation results are stored as a label image, where each segmented entity has a unique pixel value, which can serve as an identifier. It would be good to store this value in the `cell_results`, maybe as (`index_cell`) or something like that. This would allow to directly link `cell_results` with the label image.

**Comment by Henley13** [comment]
Agreed, maybe "cell_id".

**Comment by Henley13** [comment]
Issue answered in 7c13689781bf6718d6adc8f9513f506d49596c46.
