### ISSUE TITLE
[extract_cell] add sub-cellular position of isolated RNAs

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish#16]
Currently, we don't report if an RNA is in the cytoplasm or nucleus. However, this information might be useful for different biological questions.

**Comment by Henley13** [comment]
Issue answered in 542fe7aac329bbbeb49893ffe27b6b33868179a5.

I am not in favor of adding this information in extract_cell actually. This function should only match results to identified cells. Adding an information in the rna array would modify it (we should add a dimension with 0 or 1, to inform if the rna is inside or outside the region). I would prefer to operate such a distinction before, using bigfish.stack.identify_objects_in_region to split a coordinate array in two (one array with the elements inside, one with the elements outside).
