### ISSUE TITLE
Need to discriminate object inside the nucleus

### ISSUE THREAD

**Issue by Henley13** [fish-quant/big-fish#17]
We should add a generic function to tell if a specific coordinate is in the nucleus or not. It could be used with the spots, the foci, whatever.

**Comment by muellerflorian** [comment]
might be interesting to phrase this as a "general" purpose function. Rather than looking "only" at the nucleus, permitting any kind of mask for sub-cellular structure. This could come in handy for other biological questions.

**Comment by Henley13** [comment]
Issue answered in 542fe7aac329bbbeb49893ffe27b6b33868179a5.
