### ISSUE TITLE
[read_array_from_csv] add more flexibility when reading results

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish#26]
The current function reads csv files with a header and columns separated by ";".

Might be interesting to add some more flexibility. 

1. Header: yes/no; how many lines
2. Different separator

**Comment by Henley13** [comment]
I see two different use cases : 
- using a csv to store tabular data without header, but reading them as numpy ndarray matrix. 
- the same, with a header, reading them as a dataframe.

If you just read and write raw tabular data without header, I could use numpy. If you want to keep headers, I should use pandas.

**Comment by Henley13** [comment]
Actually, I use the same function to write csv files (numpy arrays are saved with np.savetxt, without header, pandas objects are saved with data.to_csv, with header if it's requested by the user). To read the csv file, I define two different functions:
- bigfish.stack.read_dataframe_from_csv() to return a pandas object (with a header)
- bigfish.stask.read_array_from_csv() to return a numpy array (without header)
