### ISSUE TITLE
read_array_from_csv: allow header rows

### ISSUE THREAD

**Issue by muellerflorian** [fish-quant/big-fish#33]
Might be useful to permit header rows in the results files when read from a csv file  (to indicate what the columns contain) . To read those, a slight modification in the function would be sufficient, by allowing access to the `skiprows` parameter of `numpy.loadtext`.

**Comment by Henley13** [comment]
If you want the values and the column name you can use `stack.read_dataframe_from_csv`. If you want to skip the header, it's a duplicate of #51. Thus, I close the issue :)
