### ISSUE TITLE
Effective error message when no spots are (pre) detected

### ISSUE THREAD

**Issue by bellonet** [fish-quant/big-fish#39]
I've accidentally entered mismatching values for voxel size and psf values to `detection.detect_spots`, resulting in no spots detected. The error message I got was the default:
`index -1 is out of bounds for axis 0 with size 0`

I think it might be helpful to tell the user that no spots were detected, and maybe they should check the input.

Values entered (for my image of simulated points): 
```
voxel_size_yx = 1
voxel_size_z = 1
psf_yx = 4
psf_z = 4
```

Otherwise, it's a great package! Very helpful.
Thanks!

**Comment by Henley13** [comment]
Hi @bellonet, thank you for the comment !

When I use these parameters in my notebook example, I cannot reproduce the error. Could you give me more context ? (the full error message with the line where it happens ? the other parameters ? your simulated image ?)

If it happens during the spot detection I suspect an error when the algorithm try to find an optimal threshold by itself.

Best,
Arthur

**Comment by Henley13** [comment]
Ok, I reproduce it with an empty image. It should be fix with 5ee4e7a2dab52f94870358b1d1e99a141d633c5f now.
Thanks again!

Arthur

**Comment by bellonet** [comment]
thank you!

**Comment by zhenzuo2** [comment]
Hi Arthur,

Could you please explain a little more about what psf_yx and psf_z means? Thank you.

Zhen
