### ISSUE TITLE
decompose_cluster() inserting large number of invisible RNAs at edge of image

### ISSUE THREAD

**Issue by marykthompson** [fish-quant/big-fish#42]
Hi, thanks for creating this great tool. I am really enjoying it.

I ran into some unusual behavior with one of my images at the decompose_cluster() step. I think it may be related to having a couple bright pixels at the very edge of the image. After decomposition, the number of spots assigned to z-slice 40 goes from 5 to 469, even though there obviously aren't many spots there. This region is then called as a focus in the detect_foci() step and ends up having >3-fold more RNAs assigned to it than any of the other foci (despite there being no visible focus in that region of the original image).

Here I’ve shown the original spots detected and I also plotted the spots in xyz with different foci shown in different colors. The strange focus with 469 ‘invisible’ RNAs is circled in red. Please let me know if there’s anything you think I should do to troubleshoot this more or if you have any ideas what might be causing it.

I put a notebook showing the analysis and the input image here:
https://github.com/marykthompson/temp_images

Thanks,
MK

![decomptest_spots](https://user-images.githubusercontent.com/17886493/109165841-f0cf6480-7773-11eb-9475-036718fcfecf.png)
![decomptest_foci_xyz_ann](https://user-images.githubusercontent.com/17886493/109165892-fe84ea00-7773-11eb-8264-7d991361fbd8.png)

**Comment by Henley13** [comment]
Hello @marykthompson,

I am sorry we did not answer you at time. I hope you were fine with your analysis nonetheless. 

From what I see in your image, you had a bunch of saturated pixels, so the behaviour of the algorithm was ok. It fill this saturated region with as many spots as it can (400+ spots). In other words, it need up to 469 regular spots to equals the intensity of this saturated region. It is probably an artefact and you can remove it from your analysis.

Best regards,

Arthur
