### ISSUE TITLE
plot.utilities.saveplot() not writing image

### ISSUE THREAD

**Issue by jstitlow** [fish-quant/big-fish#43]
I'm trying to save an image of the spot detection using plot.utilities.saveplot, as in the screenshot below. 

It writes a file, but no image. 

Any ideas?
Thanks!
j

![image](https://user-images.githubusercontent.com/5816582/109647757-b37a2680-7b27-11eb-9999-01c23aee2bb2.png)

**Comment by Henley13** [comment]
Hi @jstitlow, you should directly use the parameters `path_output=None, ext="png", show=True` in the function `plot.plot_detection()` ! The function `plot.utils.save_plot()` should not be used actually. It is just an internal routine for the rest of the package. Maybe I should rename it `_save_plot()`.

Best,
Arthur

**Comment by jstitlow** [comment]
Thanks Arthur!

I think most people will recognize the purpose of the path_output argument in plot.plot_detection(). 

I'll expose my ignorance for the benefit of other novice programmers, I didn't know you could show available arguments in Jupyter with Shift+Tab, I normally hunt them down in documentation.
