### ISSUE TITLE
Cell segmentation in 3-dimensions?

### ISSUE THREAD

**Issue by SachinDavis** [fish-quant/big-fish#47]
Cells at different z-planes whose nuclei overlap in the two-dimensional projection are interpreted as a single cell. Is there any way to do cell segmentation and nucleus mask generation in 3 dimensions to avoid this issue. See the image attached.

![image](https://user-images.githubusercontent.com/44754522/112685501-0acf9600-8e4b-11eb-9e68-9639f5837cb0.png)

**Comment by Henley13** [comment]
Hi @SachinDavis, unfortunately, we do not provide any tool for 3D segmentation in Big-FISH. I think you can try the Cellpose model for that ! They have a 3D version (but I have never tested it) : http://www.cellpose.org/

**Comment by SachinDavis** [comment]
@Henley13 Just and FYI - I tried it with Cellpose and it works great! Also integrates really well with the Big-FISH workflow :)
