### ISSUE TITLE
Different thresholding for nuclei and cytoplasm

### ISSUE THREAD

**Issue by zhenzuo2** [fish-quant/big-fish#48]
Hi,

I am not sure for spot detection, can user set different thresholds for spots in nuclei and spots in cytoplasm?

**Comment by Henley13** [comment]
Hi @zhenzuo2,

I am really sorry for the late answer, but in case you (or a future user) still need it, you might be able to:
1) Perform two spot detections with two different threshold (you obtain `spots_1` and `spots_2`).
2) Use `multistack.identify_objects_in_region` to keep the spots from the regions you want.

```python
import bigfish.multistack as multistack

spots_nuc, _ = multistack.identify_objects_in_region(mask_nuc, spots_1, ndim)
spots_cyto, _ = multistack.identify_objects_in_region(mask_cyto, spots_2, ndim)
```

Best regards,

Arthur
