### ISSUE TITLE
Changing the colour on plots

### ISSUE THREAD

**Issue by SachinDavis** [fish-quant/big-fish#54]
Hi, is there a way to change the colour scheme for the plots generated in Big-FISH. The heat maps currently generated aren't ideal for my purposes.

Sachin

**Comment by Henley13** [comment]
Hi Sachin, 

I guess it is possible (and it's already the case for some plots), but I need you to give me more details. Which plot and which element within the plot do you want to modify? Are you talking about the colormap of the image ? By default it is _viridis_.
