### ISSUE TITLE
Calculating the PSF_X, PSF_Z values

### ISSUE THREAD

**Issue by SachinDavis** [fish-quant/big-fish#55]
Hi,

How would I go about calculating the standard deviation for the PSF required by the automated spot detection function as input?

Sachin

**Comment by Henley13** [comment]
Hi Sachin, 

The PSF values used for this [function](https://big-fish.readthedocs.io/en/stable/detection/spots.html#bigfish.detection.detect_spots) are computed with this [one](https://big-fish.readthedocs.io/en/stable/utils/utils.html#bigfish.stack.get_sigma). In addition, you can see our example notebook [here](https://github.com/fish-quant/big-fish-examples/blob/master/notebooks/5%20-%20Detect%20spots.ipynb/).
