### ISSUE TITLE
Stop pinning requirements in setup.py, use test to check compatybility

### ISSUE THREAD

**Issue by Czaki** [fish-quant/big-fish#57]
Package which is marked as stable should not pin exact version of requirements. 
Mature python project does not break backward compatibility until increase main version number. 
any code which will work in matplotlib 3.0.2 should work with any from 3.x.x. So markers should be >=3.0.2,<4 \

Also other packages are pinned to old versions. This force use to create separate environment to use big-fish or force them to edit sources to change `==` to `>=`. 

Only `pandas` may be problematic because they break few things when bump to 1.x.x line. But this line introduce also many improvements and force to use 0.24.0 may be to big pay to use big-fish in many projects (for example numpy 1.16.0 cannot be simple installed with python 3.8 and 3.9).

Github provides amazing tool fo open source projects which is named Github Actions and allow to automatically run even daily test to have information about any compatibility problem.

**Comment by Henley13** [comment]
Hi @Czaki,
You are right, I will try to unpin the requirements in the next release. Some default parameters might also change in scipy or numpy, but I can check that with appropriate unit tests. I think Travis should be enough to track potential compatibility problem.

**Comment by Czaki** [comment]
I suggest using GitHub actions instead of Travis. There are less problems with this provider nowadays.

**Comment by luisub** [comment]
Hi Arthur,

Is pandas still pandas 0.24.0 a requirement in this new release (0.6)?

Luis

**Comment by Henley13** [comment]
Hi @luisub,

No, v0.6 was released for a review. But I unpinned the dependencies in the `develop` branch (so hopefully, this will be included in a v0.6.1). Some unit tests are still missing, but the overall compatibility seems ok. 

For now, you can install the develop branch directly from github if needed:

`pip install git+https://github.com/fish-quant/big-fish.git@develop`

or the current commit:

`pip install git+https://github.com/fish-quant/big-fish.git@a8172b5cdcfb5559d457ea1ac490a58d7c0cf876`

Arthur

**Comment by luisub** [comment]
Hi Artur,

Thanks a lot for the response.  I was able to install Big-FISH from Github.  And now, I have an environment with both big-fish 0.6 and the latest version of cellpose (1.0.0).

Best,

Luis
