### ISSUE TITLE
Manual Cell Segmentation

### ISSUE THREAD

**Issue by charliemoffatt** [fish-quant/big-fish#58]
Is there a way within big-fish to manually segment cells, similar to the tool included in the Matlab based FISHQuant? The current methods of segmenting cells (U-net or watershed) are challenging to use for neurons, and does not allow me to segment cells the way I need to. Or, is there another program recommended to do manual segmentation in? Thanks!

**Comment by muellerflorian** [comment]
For the moment, we don't have a manual to perform manual annotations. What you would need is the results of the manual segmentation as a mask, i.e. an image where each outlined cell is a filled object with a constant (integer) value; by convention background is 0. 

One thing we could think about is using a tool developed by a former student in the lab (Wei Ouyang, @oeway ), called Kaibu (for an idea see here: https://kaibu.org/#/app). Here, all kinds of shapes can be drawn and exported in a standard file-format (geojson). We could then provide python code to generate segmentation masks from these geojson files.  

to get an idea for how reasonable this approach is, a few questions. How big are your files? How many files would you need to annotate? Is an annotation in 2D sufficient?

**Comment by charliemoffatt** [comment]
Thank you for your help!
I need to make outlines for 19 files. When each channel is split into a tif, the resulting file is ~100MB (not a projection). The Z-projections from these files are ~2MB. For this project, I only need to annotate in 2D. 
Kaibu seems to have the functionality I need, as long as I give it a max projection.

**Comment by muellerflorian** [comment]
ok. kaibu might then be a good choice. could you annotate an image with the web app linked above? if yes, could you export the annotations and send me the file (.json). i can then try to work on a python script to convert this to a mask (muellerf.research@gmail.com). 

@Henley13 . any suggestions how this masks could then be best included in the workflow? also, once implemented, where could be best place this script. might be useful for others.

**Comment by Henley13** [comment]
I guess we can implement a function in the segmentation subpackage. The inputs would be a .json file and the shape (in pixel) of the FoV. The output would be a ndarray with np.int64 dtype, one value per instance, 0 for the background, as you said. You would initialize an empty ndarray, then read the geojson data (from Kaibu it should have the same structure) and iteratively add instance masks. 

If you want to edit an old FoV, adding a cell you previously forgot, we would need a function for the opposite way.

I also have a function to merge instance masks if you ever annotate the same image part by part and ultimately need to merge the results of different ndarrays: https://big-fish.readthedocs.io/en/stable/segmentation/postprocessing.html#bigfish.segmentation.merge_labels
