### ISSUE TITLE
Pandas version 

### ISSUE THREAD

**Issue by luisub** [fish-quant/big-fish#59]
Hi all, 

Thanks a lot for developing this great software. I wanted to ask if you are planning to update the version of pandas. I noticed that you are using pandas 0.24.0. Unfortunately, this version is quite old, and it is causing some issues when I try to integrate Big-Fish with other modules or when used in Google Colab. 

Best,

Luis

**Comment by Henley13** [comment]
Hi @luisub,

Yes, that would be a good idea. We should also unpin the others dependencies if possible as suggested in #57.

**Comment by luisub** [comment]
Thanks a lot @Henley13
