### ISSUE TITLE
Failed Segmentation

### ISSUE THREAD

**Issue by IrisWEI-1996** [fish-quant/big-fish#63]
Hi, 
Thanks for the useful tool!
I'm now analyzing our own data with big-FISH. When segmenting the nuclei and cytoplasm, I failed to see the nucleus in the picture, also failed to generate a line to label the boundary as the example shows but instead, I saw some dotted line. I feel that this is weird, and found one difference from the example is that the dtype of my nuc_label is int32 instead of int64, and I changed it with astype for watershed and plot, do you have any idea why I met this problem and how to solve this? 

More about the result: 
the pictures (nucleus segments)
<img width="616" alt="image" src="https://user-images.githubusercontent.com/18130878/152001499-6fe6599d-54e1-4f42-bc72-41b219a58103.png">
(boundary segment )
<img width="454" alt="image" src="https://user-images.githubusercontent.com/18130878/152001539-801ab59d-a153-439a-a925-f0b3f9d7797a.png">

and here are the codes I used :
```
nuc_mask = segmentation.thresholding(dapi_2d, threshold=6)
nuc_mask = segmentation.clean_segmentation(nuc_mask, small_object_size=50, fill_holes=True)
nuc_label = segmentation.label_instances(nuc_mask)

# apply watershed
cell_label = segmentation.cell_watershed(posS_2d, nuc_label.astype(np.int64), threshold=0.00001, alpha=0.00001)

plot.plot_segmentation(dapi_2d, nuc_label.astype(np.uint16), rescale=True, framesize=(15, 5))
```

Many thanks if you have any suggestions!
Iris

**Comment by Henley13** [comment]
Hi @IrisWEI-1996,

Yes I have already seen this bug. Your masks are ok, but the boundary line extracted from them seems so thin, that matplotlib fails to show them correctly. Two solutions:
- You could use a bigger `framesize`.
- I should add a parameter in the plot function to allow the user enlarging the boundaries... Sometimes you want a small plot (a small framesize), but in these cases, pixel-large boundaries might fail to appear.

Could you tell me if the framesize trick is working ? Otherwise, could you give me your big-fish version and the versions of your dependencies ?

**Comment by IrisWEI-1996** [comment]
Hi Henley,

Thank you for your rapid reply and the suggestion!
Yes, the framesize works and now I can see the boundary! Another question is that I suppose the nucleus should be seen in the picture but not here, do you have any suggestions on that?

<img width="338" alt="image" src="https://user-images.githubusercontent.com/18130878/152128657-ec2d8425-3747-4f90-b1a6-96c22599095e.png">

Thanks again,
Iris

**Comment by Henley13** [comment]
Hi @IrisWEI-1996,

Good for your plot! I should definitely add a parameter to tune the boundary width if the user want to. Concerning your nuclei, I do not know. Do they appear in the image you provided in the `image` parameter ? The fluorescent label you used in this image seems to stay outside the nuclei.

Arthur

**Comment by IrisWEI-1996** [comment]
Hi @Henley13 ,

That sounds great and helpful! Many thanks for the suggestions again!
Regarding the nuclei problem, yes you are right, the original picture is with cytoplasm only. I misunderstood that it would plot an integration of two parts but now it's clear to me, and I will close this issue. 

All the best,
Iris
