### ISSUE TITLE
Sharpness measure goes below 1

### ISSUE THREAD

**Issue by michimiura** [fish-quant/big-fish#64]
Hello, I noticed that some elements in the 'sharpness measure' computed with stack.compute_focus were below 1, and this can't be by its definition.  I tested the original code in bigfish/stack/quality.py and realised that ratio_1 is overwritten after ratio_2 = np.divide(), resulting in elements < 1 in ratio_1 where original image > filtered image.  I guess this is because ratio_1 is somehow connected with ratio_default that is overwritten when ratio_2 is assigned with np.divide(..., out = ratio_default).  One simple workaround would be to have two distinct ratio_default for each ratio_1 and ratio_2... (?)

**Comment by Henley13** [comment]
Hi @michimiura,

Thanks a lot for your contribution! You are right, there is a mistake in stack.compute_focus. The `ratio_default` is overwritten somewhere and duplicate it seems to work fine. I fix the code in 0a08a3ff30fe0bd8b9c26f0aa4e9c408badf8e34 (in develop branch), it should do the job. 

Best regards,

Arthur
