### ISSUE TITLE
FISH spot intensity analysis

### ISSUE THREAD

**Issue by zwdiscover** [fish-quant/big-fish#65]
How can I do intensity analysis of all the FISH spots or a selected group of those spots

**Comment by Henley13** [comment]
Hello @zwdiscover,

What do you mean by "intensity analysis"? Once you perform a spot detection, you will have the coordinates of the spots. You could extract the pixel intensity of each detected spot if that is what you want. 

Check [this example](https://github.com/fish-quant/big-fish-examples/blob/master/notebooks/5%20-%20Detect%20spots.ipynb) for the spot detection.

Once you get the detected coordinates, you can try something like that to get the intensity for each spot:
```python
# get spot coordinates
spots = detection.detect_spots(
    images=rna, 
    voxel_size=(300, 103, 103),  # in nanometer (one value per dimension zyx)
    spot_radius=(350, 150, 150))  # in nanometer (one value per dimension zyx)

# get spot intensity
spots_intensity = rna[spots[:, 0], spots[:, 1], spots[:, 2]]
print(spots_intensity.shape)
```

The array `spots` will have a shape (nb_spots, 3) or (nb_spots, 2), if it's a 3D or 2D analysis, and `spots_intensity` will have a shape (nb_spots,). 

Best regards,

Arthur

**Comment by zwdiscover** [comment]
I want to do an intensity histogram analysis of a selected group of FISH spots with background subtracted. How can I use single molecule Gaussian fitting algorithm to extract the intensity and remove background from each spot?

**Comment by Henley13** [comment]
Ok, what you could try to give you an idea:

```python
import numpy as np
import matplotlib.pyplot as plt
import bigfish.detection as detection
```

1) Detect your spots and their coordinates.

```python
# detect spots
spots = detection.detect_spots(
    images=rna, 
    voxel_size=(300, 103, 103),  # in nanometer (one value per dimension zyx)
    spot_radius=(350, 150, 150))  # in nanometer (one value per dimension zyx)
```

2) Extract an image around each spot and fit a gaussian on this image. You can code it manually or try to reuse big-fish functions (even if they were not specifically designed for this task).

```python
# loop over your detected spots
spots_intensity = []
for spot in spots:
    
    # format spot coordinate
    spot = spot[np.newaxis, ...]
    
    # crop spot image
    spot_image = detection.build_reference_spot(
        rna, 
        spot, 
        voxel_size=(300, 103, 103), 
        spot_radius=(350, 150, 150))
    
    # case where spot is cropped at the extremity of your image frame
    if spot_image.sum() == 0:
        spots_intensity.append(0)
    
    # fit a gaussian signal on you spot image and keep the amplitude of the gaussian as the spot intensity
    else:
        parameters_fitted = detection.modelize_spot(
            spot_image, 
            voxel_size=(300, 103, 103), 
            spot_radius=(350, 150, 150))
        sigma_z, sigma_yx, amplitude, background = parameters_fitted
        spots_intensity.append(amplitude)  
```

3) Clean a bit the intensities you get and plot your histogram.

```python
# clean or filter extreme values
#spots_intensity = ...

# plot histogram
plt.hist(spots_intensity)
```

But honestly I do not know if it could work because you will fit many gaussian signals on cropped image of individual spots that might be inconsistent. 

Hope it helps.

Arthur

**Comment by buttf7** [comment]
@Henley13 I have tried to implement this in my analysis, however I have run into an issue and was hoping for some advice/clarification. 

I appear to be getting a run-time error with the parameter fitting. "RuntimeError: Optimal parameters not found: The maximum number of function evaluations is exceeded." 

Is this an issue with the parameters that I have chosen for voxel_size and spot_radius?

**Comment by Henley13** [comment]
Hi @buttf7,

The `detection.modelize_spot` function tries to fit a gaussian signal on each spot image. Doing that you could estimate the amplitude and a background value for each spot. Then by plotting a histogram of these estimated amplitudes you would get your results. Under the wood, it's an optimization problem that fits gaussian parameters. What your error message tells you is that it fails to fit a gaussian signal to your spot image. It might come from an ill-conditioned problem, ie. the spot image you provide is wrong. I guess the problem happens earlier in the code, when you crop the spot image. To be sure I would need more information, like the complete error message and the code you use.

You could start by manually checking if `spot_image` sounds right.

**Comment by Henley13** [comment]
To do what you want, there is also another solution:

1. Detect your spots and their coordinates.

2. Remove background value globally on the full image. 

You can do this with the functions [`stack.remove_background_mean`](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#bigfish.stack.remove_background_mean) (works in 2D only) or [`stack.remove_background_gaussian`](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#bigfish.stack.remove_background_gaussian) (works in 3D and 2D)

```python
rna_no_background = stack.remove_background_mean(rna) 
```

3. Get the intensity for each spot coordinates from the "cleaned" image (instead of the original one).

```python
spots_intensity = rna_no_background[spots[:, 0], spots[:, 1]]
```

4. Clean a bit the intensities you get and plot your histogram.

**Comment by buttf7** [comment]
> To do what you want, there is also another solution:
> 
> 1. Detect your spots and their coordinates.
> 2. Remove background value globally on the full image.
> 
> You can do this with the functions [`stack.remove_background_mean`](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#bigfish.stack.remove_background_mean) (works in 2D only) or [`stack.remove_background_gaussian`](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#bigfish.stack.remove_background_gaussian) (works in 3D and 2D)
> 
> ```python
> rna_no_background = stack.remove_background_mean(rna) 
> ```
> 
> 3. Get the intensity for each spot coordinates from the "cleaned" image (instead of the original one).
> 
> ```python
> spots_intensity = rna_no_background[spots[:, 0], spots[:, 1]]
> ```
> 
> 4. Clean a bit the intensities you get and plot your histogram.

Hey, thank you for following up. I implemented the code that was referenced. However, the intensity values that were consolidated contained a significant number of zero values. I had a confusion with regards to this, considering that the intensity detection should only occur at the detected spots, I am unsure of what is being represented.

**Comment by Henley13** [comment]
Indeed, but I can't help without the code... Maybe your filtering was too strong. Try [`stack.remove_background_gaussian`](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#bigfish.stack.remove_background_gaussian), but with different sigma values.

**Comment by muellerflorian** [comment]
hello, just wanted to add my 5 cents. maybe it's preferable to **use the raw image to extract the intensity values**, rather than the filtered image? like this image intensities are not affected by some filtering operation.

**Comment by Henley13** [comment]
> hello, just wanted to add my 5 cents. maybe it's preferable to **use the raw image to extract the intensity values**, rather than the filtered image? like this image intensities are not affected by some filtering operation.

Sorry @buttf7 I mistake you with @zwdiscover. That was @zwdiscover who wanted to extract the spot intensity cleaned from the background noise. Actually @buttf7 you should try the code I mention in my first answer (if you don't care to get the background subtracted):

```python
# get spot coordinates
spots = detection.detect_spots(
    images=rna, 
    voxel_size=(300, 103, 103),  # in nanometer (one value per dimension zyx)
    spot_radius=(350, 150, 150))  # in nanometer (one value per dimension zyx)

# get spot intensity
spots_intensity = rna[spots[:, 0], spots[:, 1], spots[:, 2]]
print(spots_intensity.shape)
```

If you still get an error, we can't really do much without a reproducible example. 

Best,

Arthur

**Comment by buttf7** [comment]
I had a question with regards to this, is it possible to make the intensity extraction specific to the cells?

**Comment by Henley13** [comment]
@buttf7 you want to compute an intensity histogram only for spots detected in one specific cell ? One intensity histogram per identified cell ?

**Comment by buttf7** [comment]
Yes

**Comment by lc1497** [comment]
Is it possible to get the coordinates of the spots that were detected inside the segmented cells? Something like a table with the cell ID and the coordinates of each spot would be useful. That way, the spots inside the cell could be matched to both cell id and their intensity from the original image.

**Comment by Henley13** [comment]
Hi @lc1497, with the function [bigfish.multistack.extract_cell](https://big-fish.readthedocs.io/en/0.6.2/classification/extraction.html#bigfish.multistack.extract_cell) you assign detected spots to the segmented cells. You can also provide an image that will be cropped around the segmented cell. From that it's straightforward to get the spot intensity distribution for a specific cell. 

You can find an example of such _cell extraction_ [here](https://github.com/fish-quant/big-fish-examples/blob/master/notebooks/6%20-%20Extract%20cell%20level%20results.ipynb).
