### ISSUE TITLE
Fail to import multistack module

### ISSUE THREAD

**Issue by zwdiscover** [fish-quant/big-fish#66]
Hi, I got a problem to import the module of multistack when trying to run the first Jupyter notebook example (my python version is 3.9.7) : 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/var/folders/45/8191dpy56n373_4kt1cgwb2w0000gn/T/ipykernel_35809/740557443.py in <module>
      2 import bigfish
      3 import bigfish.stack as stack
----> 4 import bigfish.multistack as multistack
      5 print("Big-FISH version: {0}".format(bigfish.__version__))

ModuleNotFoundError: No module named 'bigfish.multistack'

**Comment by zwdiscover** [comment]
Hi, I just realized this was a python compatibility problem. If I created a new conda environment with an older Python version 3.6.13, the problem solved. I think this multistack module is not compatible with the newest Python version, at least for the case of v3.9.7.

**Comment by Henley13** [comment]
Hello @zwdiscover,

The subpackage `bigfish.multistack` is new in big-fish v0.6.0, so I think you just needed to update you big-fish version. On my side it's working fine with python 3.9.7. 

In your previous environment, just run:

```bash
pip install --upgrade big-fish
```

Arthur

**Comment by zwdiscover** [comment]
I just tried your suggestion but still failed. The version for big-fish was still v0.3.0, so weird. Only my new conda environment with Python 3.6.13 was installed with big-fish v0.6.0 by default.

**Comment by Henley13** [comment]
So the notebook is working with big-fish >= 0.6.0, right?

I do not know why you still have big-fish 0.3.0 in your original environment. What command did you run? What was the error message if any?

**Comment by zwdiscover** [comment]
Yes, the notebook is working with big-fish 0.6.0. 
I always used "pip install big-fish" to install bigfish under different conda environment. Under anaconda/python v3.6.13, the default installing version for bigfish is v0.6.0. However, under anaconda/python v3.9.7 and anaconda/python v3.10.0, the default installing version for bigfish is v0.3.0. I tried different conda environment on two different mac computers: mac mini and macbook air. The same problem existed. Looks very strange to me.

**Comment by Henley13** [comment]
So could you try `pip install --upgrade big-fish` in these environment? Then you can check you big-fish version with `pip list`.

**Comment by zwdiscover** [comment]
I ran the upgrade command as well. But after this, the version for big-fish was still v0.3.0 under python v3.9.7 and v3.10.0.

**Comment by Henley13** [comment]
Ok I reproduced the error. Indeed, big-fish v0.6.0 is installing with python 6 and 7, but not with the more recent versions. The problem comes from the pinning dependencies in big-fish (scikit-learn==0.21.0 specifically). In the next version, unpinning dependencies and a more recent version of scikit-learn will solve the problem. Until then you should downgrade your python version unfortunately.

**Comment by Henley13** [comment]
Hi @zwdiscover, I just released 0.6.1. Normally if you set up a new environment with python 3.8+, you should be able to install big-fish 0.6.1. 

Arthur

**Comment by zwdiscover** [comment]
Thanks for letting me know. I uninstalled previous version in my current environment and reinstalled it. It is running in the newest version 0.6.1 now. I further tested two of the notebooks using the multistack module. Working well now.

**Comment by Henley13** [comment]
Take care, I also updated the notebook repository.
