### ISSUE TITLE
Jupyter Notebook Tutorials won't launch

### ISSUE THREAD

**Issue by rahedges** [fish-quant/big-fish#71]
The notebooks pointed to by the link on the main page ( https://mybinder.org/v2/gh/fish-quant/fq-imjoy/binder?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Ffish-quant%252Fbig-fish-examples%26urlpath%3Dtree%252Fbig-fish-examples%252Fnotebooks%26branch%3Dmaster )
fail with this error:

> Step 40/53 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir -r "requirements.txt"
 ---> Running in 5b17aeb977fd
Collecting big-fish==0.6.2
  Downloading big_fish-0.6.2-py3-none-any.whl (123 kB)
ERROR: Could not find a version that satisfies the requirement imjoy>=0.11.38 (from versions: 0.7.20, 0.7.22, 0.7.24, 0.7.25, 0.7.26, 0.7.28, 0.7.30, 0.7.31, 0.7.40, 0.7.41, 0.7.50, 0.7.51, 0.7.52, 0.7.53, 0.7.54, 0.7.56, 0.7.57, 0.7.58, 0.7.59, 0.7.60, 0.7.63, 0.7.64, 0.7.65, 0.7.66, 0.7.67, 0.7.68, 0.8.7, 0.8.8, 0.8.13, 0.8.14, 0.8.16, 0.8.17, 0.8.18, 0.8.19, 0.8.20, 0.8.21, 0.8.22, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.12, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.4, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.11.11, 0.11.12, 0.11.13, 0.11.14, 0.11.15, 0.11.16, 0.11.17, 0.11.18, 0.11.20)
ERROR: No matching distribution found for imjoy>=0.11.38

**Comment by muellerflorian** [comment]
hello, sorry this might have happened due to a not validated update of some requirements. I hopefully fixed this. Could you give it another try?

**Comment by rahedges** [comment]
Yes, working now.  Thanks!
