### ISSUE TITLE
Cell Segmentation - Cell Information Extraction

### ISSUE THREAD

**Issue by buttf7** [fish-quant/big-fish#73]
Hello, I have been using the cellpose algorithm for cell and nuclei segmentation. The segmentation appears to work well, however when I proceed to perform cell information extraction. It severely underrepresents the number of cells present. For instance, for the image provided it says only 12 cells are detected. 
![image](https://user-images.githubusercontent.com/103357482/175981767-cc76ad2b-0c1d-42bd-96a0-09be0c4c7891.png)

**Comment by Henley13** [comment]
Hi @buttf7,
Could you give us more detail about your problem? A piece of code and the image/mask used to have a reproducible example?

**Comment by buttf7** [comment]
I apologize for the late reply. I did figure out the issue. I however, did have another inquiry is there a way to extract the intensity of spots detected inside the cell?

**Comment by Henley13** [comment]
Ok, good. There is already an issue opened about the spot intensity (#65), so I will close this one.
