### ISSUE TITLE
Threshold setting does not target elbow in plot

### ISSUE THREAD

**Issue by heike-s** [fish-quant/big-fish#74]
Hello, 

I'm trying to use the automated threshold detection feature of bigfish. However, I find that the threshold is constantly estimated to be too high, leading to a lot of missed spots.

When looking at the elbow plot, you can clearly see the elbow to the left of the set threshold, and the selected threshold does not actually lie on top of any bend in the line. Any idea what could be the reason for this and how to improve the threshold setting?

Thanks for your help!

![sample_elbow](https://user-images.githubusercontent.com/38114253/181630020-d1193595-75a8-4a34-a2c2-ef4967f66637.png)

**Comment by Henley13** [comment]
Hi @heike-s,

Indeed, you elbow plot is not really relevant. You would expect something like that instead: [spots_elbow.pdf](https://github.com/fish-quant/big-fish/files/9220737/spots_elbow.pdf).

Can you share the related image to see what could be the problem? And your code? Sometimes, if the image is not populated enough or too noisy, the threshold selection can dramatically fail. It's an heuristic function, that can help and often save time from tuning parameters, but it can fail in some specific cases. Ultimately, if we cannot solve the problem, you will need to select the threshold manually.

**Comment by heike-s** [comment]
Hi @Henley13 ,

I have really large images, in which I try to detect thousands of spots, and yes, they are definitely on the noisy side and in some channels not very well populated as well. 

I found that when I limit the threshold range in the _get_candidate_thresholds function, it actually dramatically improves the threshold detection and it works for me now. It seems that the percentile function for limiting the end range is selecting a value that is too high for the heuristic function to detect the elbow, probably - like you said - because the images are not populated enough. However, if I reduce the end range value (here I just divided the value from np.percentile by 4), the elbow detection works: 

![sample_elbow_new](https://user-images.githubusercontent.com/38114253/181797924-784ce281-84ed-4317-9ba9-1bea67ca86fb.png)

**Comment by Henley13** [comment]
Good to know. You can also apply the function `bigfish.detection.detect_spots` on a list of images, instead of one individual image. If you provide a list, it will try to infer a good threshold with all the spots detected across all the images, at once. This can be helpful if you have multiple images with few spots.
