### ISSUE TITLE
Update installation to python 3.9

### ISSUE THREAD

**Issue by ewallace** [fish-quant/big-fish#77]
Hello,
Could you update the installation instructions to python 3.9 (or similar)?

Current [installation instructions for v0.6.2](https://big-fish.readthedocs.io/en/stable/) say `conda create -n bigfish_env python=3.6`, however python 3.6 is not in the current release of conda (I used conda 4.12.0). 

I instead installed with python 3.9:
```
conda create -n bigfish_env python=3.9
source activate bigfish_env
pip install big-fish
```

Installation on my machine with Mac OS 12.3.1 worked within minutes.
Then all big-fish-examples notebooks worked for me very smoothly within 30 minutes. 
**Except tensorflow** (U-net). I briefly describe my problems with tensorflow in another issue ticket: https://github.com/fish-quant/big-fish-examples/issues/12.

Thank you for making such an easy to install and well-documented package, I hope this feedback helps!

**Comment by Henley13** [comment]
Hi @ewallace,

Thank you for your feedback. Normally the installation for python {3.6-3.9} should be the same. Or at least from the user perspective it should be the same. On travis, for every release the requirements and a bunch of unit tests are run for python 3.6, 3.7, 3.8 and 3.9. The only exception is TensorFlow indeed. Its installation is optional and not needed to run most of the package. Currently in my travis process, TensorFlow is not tested.

As a solution, I should update the documentation and the readme to _generalize_ the installation instruction for different python versions. I should check in detail the installation of TensorFlow with your dedicated issue.
