### ISSUE TITLE
How to use 3d Array Image in BigFish

### ISSUE THREAD

**Issue by ahratul** [fish-quant/big-fish#79]

**Comment by Henley13** [comment]
Hi @ahratul, 
Do you mean 3D bioimage, built with several 2D z-stack ?
You can use 3D or 2D images in bigfish.detection and 2D images only in bigfish.segmentation. If necessary, you can project your image in 2D with [bigfish.stack](https://big-fish.readthedocs.io/en/stable/stack/preprocessing.html#project-images-in-2d).

**Comment by ahratul** [comment]
Hi @Henley13 
Thank you very much
