### ISSUE TITLE
BIG-FISH or FISH-quant v2?

### ISSUE THREAD

**Issue by luisub** [fish-quant/big-fish#80]
Hi Arthur, I am writing a methods section and I am citing this software. I am unsure how to refer to it. 

Should I use something like "Spot quantification was performed using BIG-FISH \cite{Imbert2022}"   or
"Spot quantification was performed using FISH-quant v2 \cite{Imbert2022}"  ? 

Best,

Luis

**Comment by muellerflorian** [comment]
Hey Louis,

I think either one is fine, if you used specifically big-fish. Maybe a combination of both?

Spot quantification was performed using the BIG-FISH Package of FISH-quant v2 \cite{Imbert2022}"

Best
Florian

**Comment by luisub** [comment]
> 

Thank you so much!
