### ISSUE TITLE
3D segmentation 

### ISSUE THREAD

**Issue by valerialat** [fish-quant/big-fish#81]
I am using Big-FISH to perform 3D RNA quantification using multiple z-stack images.
I would also like to localize my transcript in 3D. Specifically, quantify how many are in the nucleus/cytoplasm.
Is there a way to use Big-FISH with 3D segmentation, using  3D mask from CellPose for example?

**Comment by muellerflorian** [comment]
Hello, sorry for the late reply. Unfortunately, we currently don't support 3D detection. 

Your request has been the first one going in this direction, if other users feel that this could be important, we could add this to the roadmap.

**Comment by Boehmin** [comment]
This feature would be incredibly useful!

**Comment by Henley13** [comment]
Hi @valerialat and @Boehmin, you can already detect spots in 3D with [bigfish.detection.detect_spots](https://big-fish.readthedocs.io/en/stable/detection/spots.html#bigfish.detection.detect_spots). 

You can also project your 3D RNA point cloud into your 3D segmentation masks using [bigfish.multistack.identify_objects_in_region](https://big-fish.readthedocs.io/en/stable/classification/extraction.html#bigfish.multistack.identify_objects_in_region
) or [bigfish.multistack.extract_cell](https://big-fish.readthedocs.io/en/stable/classification/extraction.html#bigfish.multistack.extract_cell). Both functions accept now a 3D segmentation mask as input. Note that if you provide a 3D spot detection coordinates with a 2D segmentation mask, RNA coordinates will be projected in 2D. 

This feature is available in the `develop` branch and will be released with the version 0.6.3, so do not hesitate to share any potential bug.
